### PR TITLE
Add the possibility of editing steps and triggers after workflow activation

### PR DESCRIPTION
**Pull request by justusdieckmann**
Depends on the subplugin,
already implemented for all in-repo steps and startdatedelay trigger

### CODE REVIEW

**Comment by NinaHerrmann** [comment]
Thanks @justusdieckmann 
I will post issues as I discover them.
The first thing which I saw was that the warning message when adjusting workflows might be misleading. This should be changed to sth. like 
`be careful dependent on the step/trigger adjustments can be made`.
image

**Review by Laur0r — CHANGES_REQUESTED** [review]
Thank you for the nice software engineering! Sadly, we assume frontend-users are likely to draw wrong assumptions. Therefore, we would suggest to include a warning message to all triggers which explicitly states that changes to the trigger setting will not affect any courses already triggered. Moreover, it would be nice to highlight settings which cannot be changed after was activated.

**Comment by justusdieckmann** [comment]
I added the trigger warning to the normal warning message, however I think highlighting not editable settings could be a bit annoying, because depending how to highlight the settings, I do not really see a good way to do this in the common step/trigger handling, but instead I believe it must probably be done per subplugin in the extend_add_instance_form_definition methods

**Comment by Laur0r** [comment]
Thank you @justusdieckmann!

**Pull request merged**
