### PR TITLE
feature/disableworkflow

### PR DESCRIPTION
**Pull request by yorickreum**
This feature by the university of Würzburg adds two disabling possibilites for workflows:

- One to just disable a workflow (while all processes keep running, but new processes wont't get triggerd for the disabled workflow).
- Another one to disable a workflow and delete all processes created by the workflow.

Hence, this feature is furthermore necessary if one wants to delete a workflow (which has been activated before).

### CODE REVIEW

**Comment by tobiasreischmann** [comment]
In a telefon conference, we decided that:
- Deactivated workflows can not be edited.
- We add a link below the table workflow definitions leading to a new view listing all deactivated workflows
- The workflow definitions table contains only non active non deactivated workflows.

**Comment by yorickreum** [comment]
Finished most of the requested/decided changes now. Some things still need some fine tuning, the phpunit tests still need to be finished.
One question thereby: Why do we have "time activated" and the "is active" flag in the database? Isn't "is active" redundant / can be calculated from "time activated" and "time deactivated"?

**Comment by yorickreum** [comment]
render_demand_confirm() in line 263 of workflow_manager.php is an unsolved problem. $PAGE ist not necessarily set. How to render demand confirm correctly in general?

**Comment by tobiasreischmann** [comment]
Thanks for your nice work. The code looks good and the features are almost as expected. I added the required "The table of active workflows needs to get additional actions (copy)." so active workflows can be copied as well. Also I duplicated the actions for the manual workflows, because we want to be able to deactivate and copy those, as well.

**Comment by tobiasreischmann** [comment]
Could you have a look at my changes?
Further there is currently a TODO in the behat test suite. It would be nice, if you could add those missing tests.
About the render_demand_confirm: The better way is probably to work with something like the action_link. I think this can be combined with a `new confirm_action(...)`, which would create a confirmation popup instead of redirecting the user to a new page.

**Comment by yorickreum** [comment]
Your changes look good to me!
I just changed the confirmation to use confirm_action() popups and added the missing test.

**Comment by tobiasreischmann** [comment]
Thanks a lot for your work here! Very nice to have the workflow lifecycle implemented now.

**Pull request merged**
