### PR TITLE
Refined 'specificdate'-trigger, so it works and triggers 'todays'-date. issue#147

### PR DESCRIPTION
**Pull request by FelixDiLenarda**
As i described in issue#147, the specificdate-trigger was buggy and somewhat complicated.
I refined it so it works properly and also triggers the courses if the date of 'today' is put in the settings.
The old logic didn't trigger if the Workflow with a specificdate-trigger of today was activated.
Greetings ;)

### CODE REVIEW

**Comment by justusdieckmann** [comment]
Hi @FelixDiLenarda,

thank you very much for this much needed bug fixing, refactoring and simplifying!

I have added the commit 2120209d2ee2b53ea4a7f36f48a9f55748abf3cc, because your help message didn't show up, and the trigger still didn't trigger for me when putting in today's date, which was caused by supplying `timelastrun` with time() in the trigger creation. Do these changes make sense to you?

Cheers,
Justus

**Comment by FelixDiLenarda** [comment]
> Hi @FelixDiLenarda,
> 
> thank you very much for this much needed bug fixing, refactoring and simplifying!
> 
> I have rebased your commit onto the master and added the commit [2120209](https://github.com/learnweb/moodle-tool_lifecycle/commit/2120209d2ee2b53ea4a7f36f48a9f55748abf3cc), because your help message didn't show up, and the trigger still didn't trigger for me when putting in today's date, which was caused by supplying `timelastrun` with time() in the trigger creation. Do these changes make sense to you?
> 
> Cheers, Justus

Hi @justusdieckmann,

thanks a lot for your replay and the enhancements. Meanwhile i fixed the same bugs locally but unfortunately forgot to publish them here.

Greetings Felix :)

**Comment by FelixDiLenarda** [comment]
Thanks for accepting and enhancing ;)

**Comment by FelixDiLenarda** [comment]
Still needs to be integrated into the Master branch.

**Comment by justusdieckmann** [comment]
Hey @FelixDiLenarda,

thats right, I was waiting for your approval :)

Thank you again!

**Pull request merged**
